name: Build

on:
  push:

jobs:
  dsw-tdk:
    name: DSW TDK
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: DSW-TDK Verify
      run: |
        dsw-tdk verify

    - name: DSW-TDK Package
      run: |
        dsw-tdk package
